In [34]:
import pandas as pd
import numpy as np

In [5]:
data = pd.read_csv("anxiety_attack_dataset.csv")

In [6]:
data.head()

,ID,Age,Gender,Occupation,Sleep Hours,Physical Activity (hrs/week),Caffeine Intake (mg/day),Alcohol Consumption (drinks/week),Smoking,Family History of Anxiety,Stress Level (1-10),Heart Rate (bpm during attack),Breathing Rate (breaths/min),Sweating Level (1-5),Dizziness,Medication,Therapy Sessions (per month),Recent Major Life Event,Diet Quality (1-10),Severity of Anxiety Attack (1-10)
0,1,56,Female,Other,9.6,8.3,175,6,No,No,4,145,33,3,No,No,4,Yes,9,10
1,2,46,Male,Teacher,6.4,7.3,97,6,No,No,3,143,18,5,Yes,No,0,No,9,8
2,3,32,Female,Doctor,6.9,1.0,467,14,No,No,2,60,34,1,No,No,7,Yes,10,5
3,4,60,Male,Doctor,9.2,3.7,471,16,No,Yes,6,94,19,1,No,Yes,4,Yes,5,8
4,5,25,Male,Student,9.2,2.5,364,2,No,Yes,7,152,15,4,No,Yes,0,No,1,1

this prints the top 5 rows of the table.

In [7]:
data.describe()

,ID,Age,Sleep Hours,Physical Activity (hrs/week),Caffeine Intake (mg/day),Alcohol Consumption (drinks/week),Stress Level (1-10),Heart Rate (bpm during attack),Breathing Rate (breaths/min),Sweating Level (1-5),Therapy Sessions (per month),Diet Quality (1-10),Severity of Anxiety Attack (1-10)
count,12000.00000,12000.00000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000
mean,6000.50000,40.96675,6.482650,5.030892,246.696083,9.492833,5.462250,119.398500,25.462333,2.987417,4.518417,5.497333,5.507583
std,3464.24595,13.47328,2.014885,2.889000,144.487071,5.769364,2.897201,34.806711,8.090686,1.414482,2.866010,2.867579,2.858663
min,1.00000,18.00000,3.000000,0.000000,0.000000,0.000000,1.000000,60.000000,12.000000,1.000000,0.000000,1.000000,1.000000
25%,3000.75000,29.00000,4.800000,2.500000,122.000000,5.000000,3.000000,89.000000,18.000000,2.000000,2.000000,3.000000,3.000000
50%,6000.50000,41.00000,6.500000,5.000000,244.000000,9.000000,5.000000,119.000000,25.000000,3.000000,5.000000,5.000000,6.000000
75%,9000.25000,53.00000,8.200000,7.525000,371.000000,15.000000,8.000000,149.000000,32.000000,4.000000,7.000000,8.000000,8.000000
max,12000.00000,64.00000,10.000000,10.000000,499.000000,19.000000,10.000000,179.000000,39.000000,5.000000,9.000000,10.000000,10.000000

this gives detailed info about the table.

In [9]:
data["Sleep Hours"].mean()

6.4826500000000005

this shows the avg hours of sleep taken by heart patients.

In [15]:
data["Age"].median()

41.0

this shows the median age.

In [16]:
data["Age"].mode()

0    43
Name: Age, dtype: int64

this shows the mode add.

In [17]:
data.groupby("Gender")["Age"].mean()

Gender
Female    41.005681
Male      40.948454
Other     40.707265
Name: Age, dtype: float64

we get the avg age for heart attack patients with respect to age.

In [24]:
smoking_counts=data["Smoking"].value_counts()

In [25]:
smoking_yes_count = smoking_counts.get('Yes', 0)
print(f"Number of people smoking: {smoking_yes_count}")

Number of people smoking: 3583

this give the number of people smoking

this gives total size of data

In [38]:
print(smoking_counts)

Smoking
No     8417
Yes    3583
Name: count, dtype: int64

this give how many people are smoking in the data.

In [46]:
smoking_to_severity = data.groupby("Smoking")["Severity of Anxiety Attack (1-10)"].mean()
print(smoking_to_severity)

Smoking
No     5.522039
Yes    5.473625
Name: Severity of Anxiety Attack (1-10), dtype: float64

this gives the avg of severity of heart attack patients with respect to smoking.